name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest, macOS-latest, windows-latest]
      fail-fast: false
      max-parallel: 4
      fail-fast: false
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' 
        java-version: '17'
    - run: java -jar build/moblima.jar 