name: JDK Build Compatibility

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
      max-parallel: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
        run: java -jar ./lib/junit-5.8.1/junit-platform-console-standalone-1.9.1.jar --class-path './test' --scan-class-path
